server:
    port: 8100
spring:
  main:
    banner-mode: off
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: taco
      hikari:
        connection-test-query: select 1
        connection-timeout: 10000
        initialization-fail-timeout: -1
        maximum-pool-size: 10
        max-lifetime: 1800000 # Default (30 minutes)
        minimum-idle: 0
        idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update

